/*

 GOL_TILEMAP_TEST1.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 5
   Tile set      : C:\Users\a\Documents\Spiele\own_original\GameBoy_GOL\GOL_4by4.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define GOL_tiles_testWidth 5
#define GOL_tiles_testHeight 5
#define GOL_tiles_testBank 0

unsigned char GOL_tiles_test[] =
{
  0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x02,0x03,0x04,
  0x00,0x05,0x06,0x07,0x08,0x00,0x09,0x0A,0x0B,0x0C,
  0x00,0x0D,0x00,0x00,0x00
};

/* End of GOL_TILEMAP_TEST1.C */
