/*

 GOL_TILEMAP_TEST1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 5 x 5
   Tile set      : C:\Users\a\Documents\Spiele\own_original\GameBoy_GOL\GOL_4by4.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define GOL_tiles_testWidth 5
#define GOL_tiles_testHeight 5
#define GOL_tiles_testBank 0

extern unsigned char GOL_tiles_test[];

/* End of GOL_TILEMAP_TEST1.H */
